# -*- coding: utf-8 -*-
"""samp_visuals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11b1thXmGTySR3tcBZMbyElvrJ5EnlmLx
"""

!pip install GDAL
!pip install imagecodecs
!pip install rasterio

import os
import rasterio
import numpy as np
import imageio

from skimage import img_as_float
from matplotlib import pyplot as plt
from PIL import Image
from rasterio.plot import show
from osgeo import gdal

from matplotlib import rcParams

rcParams['figure.figsize'] = 15, 15

# Open image
img_path = ''
mask_path = ' '

patch_sample = gdal.Open(img_path)

mask = imageio.imread(mask_path).astype(int)
labels, count = np.unique(mask[:,0], return_counts = True)


# Check number of bands
print("- Number of bands in the image: ",patch_sample.RasterCount)
print("- Labels and corresponding pixels in the mask: ",labels, count)

# Get specific bands 
band1 = patch_sample.GetRasterBand(1).ReadAsArray()
band2 = patch_sample.GetRasterBand(2).ReadAsArray()
band3 = patch_sample.GetRasterBand(3).ReadAsArray()
#band4 = patch_sample.GetRasterBand(4).ReadAsArray()
#band5 = patch_sample.GetRasterBand(5).ReadAsArray()
#band6 = patch_sample.GetRasterBand(6).ReadAsArray()
#band7 = patch_sample.GetRasterBand(7).ReadAsArray()
#band8 = patch_sample.GetRasterBand(8).ReadAsArray()
#band9 = patch_sample.GetRasterBand(9).ReadAsArray()
#band10 = patch_sample.GetRasterBand(10).ReadAsArray()
#band11 = patch_sample.GetRasterBand(11).ReadAsArray()
#band12 = patch_sample.GetRasterBand(12).ReadAsArray()
#band13 = patch_sample.GetRasterBand(13).ReadAsArray()
#band14 = patch_sample.GetRasterBand(14).ReadAsArray()
#band15 = patch_sample.GetRasterBand(15).ReadAsArray()
#band16 = patch_sample.GetRasterBand(16).ReadAsArray()
#band17 = patch_sample.GetRasterBand(17).ReadAsArray()
#band18 = patch_sample.GetRasterBand(18).ReadAsArray()
#band19 = patch_sample.GetRasterBand(19).ReadAsArray()
#band20 = patch_sample.GetRasterBand(20).ReadAsArray()
#band21 = patch_sample.GetRasterBand(21).ReadAsArray()
#band22 = patch_sample.GetRasterBand(22).ReadAsArray()
#band23 = patch_sample.GetRasterBand(23).ReadAsArray()



# it can only show 4 channels, you can check combination of 4 channels
#img = np.dstack((band4,band5,band3)) # Near-IR, mid-IR, red = land-water boundaries
img = np.dstack((band3,band2,band1)) # flooded areas and vegetated areas
#img = np.dstack((band4,band5,band1)) # Vegetation

fig, ax = plt.subplots(1,2)
ax[0].imshow(img)
ax[1].imshow(mask)

# sanity check for raster data shape
#samp_path = ''
#samp = img_as_float(imageio.imread(samp_path))
#print("image shape: ", samp.shape)
#print("mask shape: ", mask.shape)
#print(type(samp))